server:
  port: 8080

spring:
  application:
    name: vc-chat-sample
  aop:
    auto: true
    proxy-target-class: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      #获取用户信息url
      user-info-uri: http://localhost:9999/me
    client:
      #获取token url
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
      #身份
      client-id: acme
      client-secret: acmesecret
      scope: openid

management:
  security:
    enabled: false

logging:
  level:
    root: info