server:
  port: 8080

spring:
  application:
    name: vc-chat-sample
  aop:
    auto: true
    proxy-target-class: true
  http:
    multipart:
      max-request-size: 100Mb
      max-file-size: 100Mb

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      #获取用户信息url
      user-info-uri: http://localhost:9999/me
    client:
      #获取token url
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
      #身份
      client-id: acme
      client-secret: acmesecret
      scope: openid

hystrix:
  threadpool:
    default:
    #并发执行的最大线程数，默认10
      coreSize: 200
      #BlockingQueue的最大队列数
      maxQueueSize: 200
      #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      queueSizeRejectionThreshold: 200
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 60000


ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
#  MaxAutoRetries: 1 # 最大重试次数
#  MaxAutoRetriesNextServer: 10 #最大出错10次,将排除调用列表

management:
  security:
    enabled: false

logging:
  level:
    root: info
