server:
  port: 8082


spring:
  application:
    name: vc-chat-logic
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost/vc_chat?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 200
#    schema: classpath:/db/migration/V1__vc-chat.sql

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
  enabled: false

mybatis:
  mapper-locations:
    - classpath:com/vcg/chat/logic/dao/*.xml
  type-aliases-package: com.vcg.chat.model



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  threadpool:
    default:
    #并发执行的最大线程数，默认10
      coreSize: 200
      #BlockingQueue的最大队列数
      maxQueueSize: 200
      #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      queueSizeRejectionThreshold: 200
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 60000


ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
#  MaxAutoRetries: 1 # 最大重试次数
#  MaxAutoRetriesNextServer: 10 #最大出错10次,将排除调用列表

management:
  security:
    enabled: false

logging:
  level:
    root: info
    com.vcg.chat.logic.dao: debug
#  file: ${spring.application.name}.log
